### ISSUE TITLE
Feature: Create modes/states

### ISSUE THREAD

**Issue by slambert** [thec4aa/sonar-people-counter#1]
Create a way to navigate between "modes" using the LCD Button shield's interface.

You should have to confirm you want to change modes, so you don't do it accidentally.

We can use two button presses combined to enter a menu where you select the mode. Hit "select" and you choose that mode. There should also be a way to "exit"

If this is confusing I can draw it all out.

**Comment by slambert** [comment]
@lizihan030 Here's some sample code on how to create "states". I think https://gist.github.com/slambert/a219f919793cbf9b1288a2508261fd9b

[State is the proper term](https://en.wikipedia.org/wiki/State_(computer_science).

**Comment by lizihan030** [comment]
Menu page created:
Sonar
Countup
Countdown
Manual
clock(*)
